# Generated by Django 4.0.5 on 2022-06-01 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=30)),
                ('sodrzhina', models.CharField(max_length=50)),
                ('fajlovi', models.FileField(upload_to='')),
                ('datumKreiranje', models.DateField()),
                ('datumIzmena', models.DateField()),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab3.bloguser')),
            ],
        ),
    ]
