# Generated by Django 4.0.5 on 2022-06-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lab3', '0007_komentari'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Komentari',
            new_name='Komentar',
        ),
        migrations.CreateModel(
            name='Blokiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloker', to='Lab3.bloguser')),
                ('blokiran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blokiran', to='Lab3.bloguser')),
            ],
        ),
    ]
