# Generated by Django 4.0.5 on 2022-06-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab3', '0010_alter_blokiran_bloker_alter_blokiran_blokiran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fajlovi',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
    ]
