# Generated by Django 4.0.5 on 2022-06-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab3', '0011_alter_blog_fajlovi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fajlovi',
            field=models.FileField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
